--- 
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
always_allow_html: true
---


```{r global_knitr, echo = FALSE, eval = TRUE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      results = "hide",
                      fig.width = 8,
                      fig.asp = 0.7,
                      out.width = "120%")

```

```{r, packages}

library(data.table)
library(sf)
library(ggplot2)
library(MigStat)
library(plotR)
library(kableExtra)

```

```{r, funs}

read_data <- function(path, file) {
    if(grepl("prediction", path)) {
        mod <- gsub("FlowData", "", file)
        mod <- gsub("Preds", "model", mod)
    }
    if(grepl("models", path)) {
        mod <- gsub("opti_", "", file)
    }
    mod <- gsub(".csv", "", mod)
    dt <- data.table::fread(file.path(path, file))
    dt[, model := mod]
    return(dt)
}

calculate_net <- function(dt, col, by, o = "fromdist", d = "todist",
                           long = FALSE, type = NULL) {
    dt_in <- dt[, .(inflow = sum(get(col))), keyby = c(d, by)]
    dt_out <- dt[, .(outflow = sum(get(col))), keyby = c(o, by)]
    dt_in[dt_out, outflow := i.outflow, on = c(setNames(o, d), by)]
    dt_in[, net := inflow - outflow]
    setnames(dt_in, d, "region")
    if(!is.null(type)) {
        dt_in[, type := type]
        id_vars <- c("type", "region", by)
    }
    if(is.null(type)) {
        id_vars <- c("region", by)
    }
    if(long == TRUE) {
        dt_in <- melt(dt_in, id.vars = id_vars)
    }
    return(dt_in)
}

make_map <- function(netm, age) {
    plt <- ggplot(set_geom(netm[agegroup == age], F)) +
        geom_sf(aes(fill = value)) +
        facet_wrap(~variable) +
        ggtitle(sprintf("Actual and predicted nmr (normalized by pop of Germans) for age group %s", age)) +
        theme_minimal() 
    return(plt)
}

make_net_plot <- function(net, scales = "free") {
    plt <- ggplot(net, aes(preds, actual)) +
        geom_hline(yintercept = 0, col = "blue", linewidth = .2) +
        geom_vline(xintercept = 0, col = "blue", linewidth = .2) +        
        geom_point(alpha = .5) +
        facet_wrap(vars(agegroup, year), scales = scales) +
        theme_minimal() +
        ggtitle("Net migration rate(400 regions, normalized by pop of Germans)")
    return(plt)
}

plot_fit <- function(dt, x, y, th) {
    plt <- ggplot(dt[preds > th], aes({{x}}, {{y}})) +
        geom_hline(yintercept = 0) +
        geom_point(pch = ".") +
        geom_smooth(se = FALSE) +
        facet_wrap(vars(model, agegroup), scale = "free") +
        ggtitle(sprintf("Individual flows for preds > %s", th)) +
        theme_minimal()
    return(plt)
}

order_models <- function(dt) {
    model_names <- dt[, unique(model)]
    lvls <- data.table(models = model_names)
    lvls[, id := tstrsplit(model_names, "_")[[2]]]
    lvls <- lvls[order(as.numeric(id)), .(models)]
    dt[, model := factor(model, levels = lvls[, models])]
    return(NULL)
}

rec_ages <- function(dt) {
  agegroup <- NULL
  lbls <- data.table(old = c("unter18", "über65"),
                     new = c("below18", "above65"))
  dt[lbls, agegroup := i.new, on = .(agegroup = old)]
  return(NULL)
}

```

```{r read-data}

p_out <- "~/Documents/GermanMigration/plots"
p_preds <- "~/Documents/GermanMigration/predictions"
p_coefs <- "~/Documents/GermanMigration/fitted_models"
f_preds <- list.files(p_in)
f_coefs <- list.files(p_coefs, "opti")
preds_th <- 3

dt <- rbindlist(lapply(f_preds, function(x) read_data(p_preds, x)))
setnames(dt, c("flows", "preds3"), c("actual", "preds"), skip_absent = TRUE)
order_models(dt)
dt_coefs <- rbindlist(lapply(f_coefs, function(x) read_data(p_coefs, x)))
order_models(dt_coefs)
dt_coefs[, diff := values - inits]
pop_dt <- fread(file.path("~/Diss/inst/extdata/clean/aux_data/", "age17for.csv"))
setnames(pop_dt, "age_group", "agegroup")
rec_ages(pop_dt)
shp <- setDT(sf::read_sf(file.path("~/Diss/inst/extdata/clean/shapes", "districts_ext.shp")))

```

```{r, diff-plt, fig.cap = caption}

caption <- "Distribution of differences between optimal values and initial values."
ggplot(dt_coefs[startsWith(names, "desire")], aes(diff)) +
    geom_histogram() +
    facet_wrap(vars(model), scale = "free") +
    theme_minimal() +
    ggtitle("opti - init for desire coefs")

ggplot(dt_coefs[startsWith(names, "desire")], aes(values)) +
    geom_density() +
    facet_wrap(vars(model), scale = "free") +
    theme_minimal() +
    ggtitle("opti coefs")

## ggplot(dt_coefs, aes(model, diff)) +
##     geom_violin() +
##     theme_minimal() +
##     ggtitle("opti - init")

```

```{r data}

age_lvls <- c("below18", "18-25", "25-30", "30-50", "50-65", "above65")
use_age <- age_lvls
dt <- dt[agegroup %in% use_age]
dt[, agegroup := factor(agegroup, levels = age_lvls)]
dt[, resid1 := (actual - preds) / preds]
dt[, resid2 := sign(resid1) * log(1 + abs(resid1))]

dtm <- melt(dt, measure.vars = c("actual", "preds"), variable.name = "type")


## probably much easier
net <- calculate_net(dtm, col = "value",
                     by = c("year", "agegroup", "model", "type"),
                     long = TRUE)[variable == "net"]
net[pop_dt, pop := i.german, on = .(region, year, agegroup)]
net[, value := value / (pop * 1000) * 100] # in %, pop is in 1000
net <- dcast(net, region + year + agegroup + type ~ model, value.var = "value")
## net[, actual_s := sign(actual) * log(1 + abs(actual))]
## net[, preds_s := sign(preds) * log(1 + abs(preds))]
netm <- melt(net, id.vars = c("region", "year", "agegroup", "type"),
             variable.name = "model")
netm <- dcast(netm, region + year + agegroup + model ~ type)
## netm <- netm[variable %in% c("actual", "preds")]
##netm <- netm[variable %in% c("actual_s", "preds_s")]
netm[shp, geometry := i.geometry, on = .(region = AGS)]

```

```{r, coef-table, results = "show"}

kbl(dt_coefs, digits = 2, booktabs = TRUE, longtable = TRUE,
    caption = "Parameters")

```

```{r, kable-preds, results = "show"}

kbl(head(dt[order(actual)], 10),
    caption = "Predictions for smallest actual od-flows",
    digits = 2, booktabs = TRUE)
kbl(head(dt[order(- actual)], 10),
    caption = "Predictions for largest actual od-flows",
    digits = 2, booktabs = TRUE)

max_reg <- dt[actual == max(actual), .(fromdist, todist)]

## should have done a join
dt_sym1 <- dt[fromdist == max_reg[[1]] & todist == max_reg[[2]]]
dt_sym1[, type := "fromto"]
dt_sym2 <- dt[fromdist == max_reg[[2]] & todist == max_reg[[1]]]
dt_sym2[, type := "tofrom"]
dt_sym <- rbind(dt_sym1, dt_sym2)

dt_sym <- melt(dt_sym[, -c(1,2)],
     id.vars = c("agegroup", "year", "distance", "type"),
     value.var = c("preds", "actual"))

kbl(dcast(dt_sym, variable + type ~ agegroup, value.var = "value"),
    caption = "Are our predictions symmetric?",
    digits = 2, booktabs = TRUE)

```
```{r, opti-ini}

plt_change <- ggplot(dt_coefs, aes(values - inits)) +
    geom_density() 
prettify(plt_change, main = "Optimial parameters - inits", show_cap = FALSE)

```


## Maps
```{r make-maps}

netm[, diff := actual - preds]
netm2 <- melt(netm, measure.vars = c("actual", "preds", "diff"))
netm2 <- netm2[model %in% c("model3_0.1", "model3_10.0")]
netm2 <- netm2[variable == "diff"]

make_map <- function(netm) {
    plt <- ggplot(set_geom(netm, F)) +
        geom_sf(aes(fill = value)) +
        facet_wrap(vars(model, variable, agegroup)) +
        theme_minimal() 
    return(plt)
}

make_map(netm2[model == "model3_10.0"])
make_map(netm2[model == "model3_0.1"])

dt[, sum(actual), keyby = .(model)]
netm[order(actual)]

```

## Net chart
```{r net-plot}

make_net_plot(netm[variable %in% c("model3_0.1", "model3_10.0")], scales = "free") +
    facet_wrap(vars(variable, agegroup), nrow = 6)

make_net_plot(netm[variable %in% c("model3_0.1")], scales = "free") +
    facet_wrap(vars(variable, agegroup))


make_net_plot(netm[variable %in% c("model3_10.0")], scales = "free") +
    facet_wrap(vars(variable, agegroup))

make_net_plot(net, scales = "fixed") +
    coord_fixed()

```

## Individual Flows

```{r individual-resids-violin}

sub1 <- sprintf("Residuals sign(resid) * log(1 + abs(resid)), only preds > %s are shown", preds_th)
resid_plt <- ggplot(dt[preds > preds_th],
                    aes(agegroup, resid2, fill = agegroup)) +
    geom_violin() +
    facet_wrap(vars(model))
prettify(resid_plt,
         main = "Individual Flows Residuals sign(resid) * log(1 + abs(resid))",
         sub = sub1)

sub2 <- sprintf("resid = (actual - preds) / preds, only preds > %s are shown", preds_th)
resid_plt <- ggplot(dt[preds > preds_th & model %in% c("model3_0.1", "model3_10.0")],
                    aes(agegroup, resid1, fill = agegroup)) +
    geom_violin() +
    facet_wrap(vars(model))
prettify(resid_plt, main = "Individual Flows",
         sub = sub2)

```

```{r, preds-resid, eval = TRUE}


plot_fit(dt[model %in% c("model3_0.1", "model3_10.0")], distance, log(actual/preds), 0) +
    facet_wrap(vars(agegroup, model), scale = "free", ncol = 2) 


plot_fit(dt, log(preds), log(actual/preds), 3)
plot_fit(dt, preds, (actual - preds) / preds, 3)
plot_fit(dt, preds, sign((actual - preds) / preds) * log(0 + ((actual - preds) / preds)) , 1)

```

```{r}

dcast(dt, fromdist + todist + agegroup ~ model)

```
