--- 
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
always_allow_html: true
---


```{r global_knitr, echo = FALSE, eval = TRUE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      results = "hide",
                      fig.width = 6,
                      fig.asp = 0.7,
                      out.width = "100%")

```

```{r packages}

library(data.table)
library(sf)
library(MigStat)
library(ggplot2)
library(patchwork)
library(dotwhisker)
library(kableExtra)
library(helpeR)

```

```{r read-data}

read_output <- function(path, type, model = "US-model") {
    age_lvls <- c("below18", "18-25", "25-30", "30-50", "50-65", "above65")
    read_agegroup <- function(path, file) {
        dt <- data.table::fread(file.path(path, file))
        dt[, agegroup := get_age(file)]
    return(dt)
}
    get_age <- function(file) {
        age <- data.table::tstrsplit(file, "_")[[2]]
        age <- data.table::tstrsplit(age, "\\.")[[1]]
        return(age)
    }
    dt <- data.table::rbindlist(lapply(list.files(path, pattern = type),
                                       function(x) read_agegroup(path, x)))
    dt[, agegroup := factor(agegroup, levels = age_lvls)]
    dt[, model := model]
    return(dt)
}

path <- "./manuscript_input"
districts <- fread("./data/districts.csv")
dt_geog <- read_output(path, "germgeog")
dt_dens <- read_output(path, "germdensfun")
dt_flows <- read_output(path, "germflows")
dt_flows[, resid1 := (flows - preds) / preds]
dt_flows[, resid2 := sign(resid1) * log(1 + abs(resid1))]
dt_flows[districts, fromdens := i.density, on = .(fromdist = distcode, year)]
dt_flows[districts, todens := i.density, on = .(todist = distcode, year)]

dt_params <- read_output(path, "params")
shp <- setDT(sf::read_sf("~/Diss/inst/extdata/clean/shapes/districts.shp"))
shp[, AGS := as.integer(AGS)]


net <- calculate_net(dt_flows, "flows", by = c("year", "agegroup"))
net_pred <- calculate_net(dt_flows, "preds", by = c("year", "agegroup"))


dt_geog[net, net := i.net, on = .(distcode = region, year, agegroup)]
dt_geog[shp, geometry := i.geometry, on = .(distcode = AGS)]
dt_geog[districts, pop_all := i.pop, on = .(distcode, year)]
dt_geog[net_pred, net_pred := i.net, on = .(distcode = region, year, agegroup)]

ages <- dt_flows[, levels(unique(agegroup))]

```

## Model fit and diagnostic plots of individual flows
```{r impute-actual-flows}

impute_actual_zeros <- function(dt, mean = -15) {
    dt[, actual_imp := as.double(flows)]
    rnds <- rlnorm(dt[flows == 0, .N], mean, log(2.0))
    dt[flows == 0, actual_imp := rnds]
    return(NULL)
}

impute_actual_zeros(dt_flows, -10)

```

```{r model-fit, fig.cap = caption}

caption <- "Fitted v Observed from model fitted on all rows, but only positive flows shown"
plot_fit(dt_flows[flows > 0], log(preds), log(actual_imp), th_min = 0, p_sample = .1) +
    ggtitle("10 percent sample of individual flows, only for positive actual flows")

```

```{r model-fit2, fig.cap = caption}

caption <- "Fitted v Observed"
plot_fit(dt_flows, log(preds), log(actual_imp), th_min = 0, p_sample = .1) 

```

```{r, flows-distance1, eval = TRUE, fig.cap = caption}

caption <- "Distance dependence, actualimp: True 0 flows were imputed using lognormal with mean = -15"
plot_fit(dt_flows, dist, log(actual_imp / preds), th_min = 0, smooth = FALSE, p_sample = .1)
## w <- 8
## ggsave("~/Desktop/plot_imp.pdf", width = w, height = w / 1.6)

```

```{r, flows-pop, fig.cap = caption}

caption <- "Dependence on Population"
plot_fit(dt_flows, log(frompop * topop), log(actual_imp/preds),
         th_min = 0, p_sample = .1, smooth = FALSE)

```

```{r, flows-density, fig.cap = caption}

caption <- "Dependence on density"
plt1 <- plot_fit(dt_flows, log(fromdens), log(actual_imp/preds), 0, p_sample = 1, smooth = FALSE)
plt2 <- plot_fit(dt_flows, log(todens), log(actual_imp/preds), 0, p_sample = 1, smooth = FALSE)
plt3 <- plot_fit(dt_flows, log(fromdens * todens), log(actual_imp/preds), 0, p_sample = .1, smooth = FALSE)

## plt1 + plt2
plt3

```

## Desirability Maps
```{r desirability-maps, out.width = "120%", fig.width = 10, fig.caption = caption}

caption <- "Desirability Map"
make_map <- function(dt, type = c("desir", "net", "pred")) {
    type <- match.arg(type)
    age <- dt[, unique(agegroup)]
    if(type == "desir") {
        map <- ggplot(set_geom(dt, F)) +
            geom_sf(aes(fill = desirability)) +
            ggtitle(sprintf("%s, estimated desirability", age))
    }
    if(type == "net") {
        map <- ggplot(set_geom(dt, F)) +
            geom_sf(aes(fill = net / pop_all * 100)) +
            ggtitle(sprintf("%s, Net migration", age))
    }
    if(type == "pred") {
        map <- ggplot(set_geom(dt, F)) +
            geom_sf(aes(fill = net_pred / pop_all * 100)) +
            ggtitle(sprintf("%s, Predicted net migration", age))
    }
    map <- map +
        theme_bw() +
        theme(legend.position = "top") 
    return(map)
}

make_agemaps <- function(dt, type = c("desir", "net")) {
    desir_map <- make_map(dt, type[1])
    net_map <- make_map(dt, type[2])
    return(desir_map + net_map)
}

lapply(ages, function(age) make_agemaps(dt_geog[agegroup == age]))

```

## Net Migration Maps
```{r net-migration-maps,  out.width = "140%", fig.width = 10, fig.cap = caption}

caption <- "Net migration and predicted net migration"

netm <- melt(dt_geog, id.vars = c("distcode", "year", "agegroup", "geometry", "pop"),
             measure.vars = c("net", "net_pred"))

make_net_map <- function(dt) {
    plt <-  ggplot(set_geom(dt, F)) +
        geom_sf(aes(fill = value / pop * 100)) +
        facet_wrap(~variable) +
        ggtitle(sprintf("Age group: %s", dt[, unique(agegroup)]))
    return(plt)
}

lapply(ages, function(age) make_net_map(netm[agegroup == age]))

```

```{r constrain-flows,  out.width = "140%", fig.width = 10, fig.cap = caption}

rm_largest_flows_and_preds <- function(dt, n_rm = 8) {
    flows_from <- dt_flows[order(-flows), head(.SD, n_rm), keyby = .(fromdist, agegroup)]
    flows_to <- dt_flows[order(-flows), head(.SD, n_rm), keyby = .(todist, agegroup)]
    all <- rbind(flows_from, flows_to)[, .(agegroup, fromdist, todist, year)]
    setkeyv(all, colnames(all))
    setkeyv(dt, colnames(all))
    dt2 <- copy(dt) ## otherwise dt is modified in place
    dt2 <- dt[!all]
    message(sprintf("%s rows removed", nrow(all)))
    return(dt2)
}

flows_constrained <- rm_largest_flows_and_preds(dt_flows, 16)
flows_constrained <- dt_flows[fromdens < 1000 & todens < 1000]
net <- calculate_net(flows_constrained, "flows", by = c("year", "agegroup"))
net_pred <- calculate_net(flows_constrained, "preds", by = c("year", "agegroup"))
dt_geog[net, net_constrained := i.net, on = .(distcode = region, year, agegroup)]
dt_geog[net_pred, net_pred_constrained := i.net, on = .(distcode = region, year, agegroup)]


```

```{r net-scatter}

plt1 <- ggplot(dt_geog) +
    geom_point(aes(net_pred / pop * 100, net / pop * 100)) +
    geom_smooth(aes(net_pred / pop * 100, net / pop * 100), se = FALSE) +
    facet_wrap(~agegroup, scales = "free") +
    ggtitle("Unconstrained")


plt2 <- ggplot(dt_geog) +
    geom_point(aes(net_pred_constrained / pop * 100, net_constrained / pop * 100)) +
    geom_smooth(aes(net_pred_constrained / pop * 100, net_constrained / pop * 100), se = FALSE) +
    facet_wrap(~agegroup, scales = "free") +
    ggtitle("Constrained")

plt1 / plt2

cbind(dt_geog[, .(correlation_net = cor(net, net_pred)), keyby = agegroup], 
dt_geog[, .(correlation_net_constrained = cor(net_constrained, net_pred_constrained)), keyby = agegroup][, 2])


```

```{r, net-maps-constrained}

caption <- "Net migration and predicted net migration without 8 biggest flows"
netm <- melt(dt_geog, id.vars = c("distcode", "year", "agegroup", "geometry", "pop"),
             measure.vars = c("net_constrained", "net_pred_constrained"))
make_net_map(netm[agegroup == "18-25"])
make_net_map(netm[agegroup == "below18"])

```

## Density Hexbin charts
```{r density, fig.cap = caption}

caption <- "Evaluation of density cheby polynomial. For better visibility evaluated values are constrained to the 0.99 percentile. Some observations where really large, especially in the upper right corner."
make_dens_hex <- function(dt, q_max = .99) {
    max_val <- dt[, round(quantile(funval, q_max), 2)]
    main <- sprintf("%s, Density function, funval < %s (%s quantile)",
                    dt[, unique(agegroup)], max_val, q_max)
    plt <- ggplot(dt[funval <= max_val]) +
        stat_summary_hex(aes(fromdens, todens, z = funval), fun = sum) +
        ggtitle(main) +
        theme_bw()
    return(plt)
}

lapply(levels(ages), function(age) make_dens_hex(dt_dens[agegroup == age]))

```

## Optimal Parameters
```{r params-plt, fig.cap = caption}

caption <- "Estimated coefficients"
plot_coefs <- function(dt, params = c("a", "c", "d0", "dscale", "neterr", "ktopop")) {
    params <- params
    dt2 <- dt[parname %in% params, .(paramval, parname, agegroup)]
    setnames(dt2, c("parname", "paramval", "agegroup"),
             c("term", "estimate", "model"))
    plt <- ggplot(dt2) +
        geom_point(aes(model, estimate)) +
        scale_x_discrete(limits = rev) +
        coord_flip() +
        facet_wrap(~term, scale = "free") +
        theme_minimal() +
        ggtitle("Optimal Gravity Parameters")
    return(plt)
}

plot_coefs(dt_params)

```

## Further Diagnostics
```{r, invent-flows, results = "show"}

calc_flowinvention <- function(dt) {
    invent <- dt[, .(all_actual = sum(flows),
                 all_predicted = sum(preds)), keyby = .(agegroup, year, model)][
      , rel_diff := round((all_predicted - all_actual) / all_actual * 100, 2)][]
    return(invent)
}

invent <- calc_flowinvention(dt_flows)
## dcast(invent, agegroup + all_actual + all_predicted + rel_diff ~ model, value.var = "all_predicted")
kable(invent, caption = "Does our models invent flows?")

```


## Where are the biggest errors?

```{r, flow-errors}

get_districts_with_large_net_error <- function(dt, n_largest = 10) {
    dt[, net_rel_error := (net - net_pred) / pop * 100]
    dt2 <- dt[order( - abs(net_rel_error)),
                   .(distcode, agegroup, net, net_pred, net_rel_error)]
    dt2 <- dt2[, head(.SD, n_largest), keyby = agegroup]
    return(dt2)
}

filter_rows <- function(dt, dt_filter) {
    age <- dt_filter[, agegroup]
    ags <- dt_filter[, distcode]
    err <- dt_filter[, round(net - net_pred, 0)]
    dt2 <- dt[agegroup == age][fromdist == ags | todist == ags]
    dt2[, group := sprintf("net error: %s", err)]
    return(dt2)
}

plot_flows <- function(dt) {
    plt <- ggplot(dt, aes(log(flows), flows - preds)) +
        geom_point(alpha = .2) +
        geom_smooth(se = FALSE) +
        facet_wrap(~group, scales = "free") +
        ggtitle(dt[, unique(agegroup)]) +
        theme_bw()
    return(plt)
}


plot_and_save <- function(dt, age, path) {
    plot_flows(dt[agegroup == age])
    fn <- paste0(age, ".pdf")
    ggsavew(, filename = file.path(path, fn))
    return(NULL)
}

net_errs <- get_districts_with_large_net_error(dt_geog, 10)
flows_filtered <- rbindlist(lapply(1:nrow(net_errs), function(i) filter_rows(dt_flows, net_errs[i, ])))
lapply(ages, function(x) plot_and_save(flows_filtered[agegroup == x], x, "~/Desktop/plots"))

```

