---
title: Perceived Desirability The central modeling concept 
authors:
    name: Konstantin Hoffie
    affiliation: East-German
    roles: writing
    corresponding: true
engine: julia
execute:
  echo: false
  enabled: false
julia:
  exeflags: ["--project=/home/konstantin/code"]
  env: ["JULIA_NUM_THREADS=5"]
---

# Methods

```{julia}
#| label: desir-libs

using KernelDensity, Plots, Distributions, DataFrames, QuadGK
include("src/circle.jl")

function hypo!(x, centers, sigmas, fac, lbl = nothing, main = nothing)
    function f(x, c, s, f)
        y = sum(pdf(Normal(c[i], s[i]), x) ./ f[i] for i in 1 : length(c))
    end
    y = f(x, centers, sigmas, fac)
    plot!(x, y, xlab = "Distance in km", ylab = "Desirability",
         label = lbl, title = main,
          linewidth = 2, xlim = (1, x[end]))
    ##plot!([0, x[end]], [mean(y), mean(y)], label = "Smoothed")
end

```

## Desirability
Desirability is the central theoretical construct behind our migration
model. This section explains what desirability is, what it is not, and
how it can be estimated from data. 

In broad terms, we assume that people can assign a numerical
desirability value to each possible destination, including their
current home. Roughly, this desirability represents their belief, how
well overall their life goes if they move there. We do not assume
anything about their reasoning process. They may be carefully
calculating, comparing various possible destinations or they may only
have vague ideas about what they want. What matters is that, in
principle, it is possible to describe their perceived desirability as
a function of various variables. Imagine we ask someone currently
looking for a new home what she desires **to avoid this she/he. Can we in a scientific text write they?**. She responds: "I want to be
close to my family and I want to live in a city. I don't care about
expensive rents because I earn very well and I work from remote. I'm
very much into Jazz and I absolutely need a vibrant scene." We assume
that from these desires we can construct an individual desirability
function that assigns a desirability score to each region. The
function will be at least zero for each possible destination with zero
representing the lowest desirability possible. This person's
function will be close to zero outside cities and it will be
relatively large in cities, in particularly if there is a large jazz
scene and if the city is close to her family. There will
be some uncertainty in all of this. For example the jazz scene may be
vibrant now but maybe it is in decline or she underestimates the time
it takes with public transport to visit her family. All this need not
concern us here, what matters is only that for each individual there
is a function that describes this persons *perceived* desirability of
each region. In particular we assume this function is as follows:

$$
f_i : \mathbb{R}^2 \rightarrow \mathbb{R}_{\geq 0} \quad \text{and} \int_{\mathbb{R}^2} f_i(x, y) d(x, y) = \mu_i(\mathcal{R}) \quad \text{for all individuals } i
$$

$f_i$ defines a probability density over $\mathbb{R}^2$, which is zero
outside Germany's borders. Germany (or other countries where this
model is used) we denote as $\mathcal{R}$. We assume that $f_i(x, y) =
zero$, if the point $(x, y) lies outside Germany, meaning that we
ignore migrations into other countries. Sometimes it is convenient to
talk of points $(x, y) \in \mathcal{R}$, but sometimes it is more
convenient to talk of regions $r$. A region $r$ is a subset of
$\mathbb{R}^2$ and they are disjoint. Furthermore, their union is
Germany. This paper is concerned with migrations between districts.
The desirability and individual assigns to a region is defined as:

$$
\mu_i(r) = P(i \text{ moves to } r) = \frac{1}{\mu_i(\mathcal{R})} 
\int_{r \subset \mathbb{R}^2 } f_i(x, y)d(x, y) \quad \text{with }
\frac{1}{\mu_i(\mathcal{R})} \sum_{r \in \mathcal{R}} \mu_i(r) = 1
$$

That is, the desirability that $i$ assigns to $r$ is the sum of the
desirabilities that $i$ assigns to any specific point in this region.

We denote the probability that a randomly picked migration ends in
destination $r$ as

$$
\mu(r) = \frac{1}{N} \sum_{i = 1}^N \mu_i(r)
$$

**this defines a new probability measure over the set of regions, not
sure if stating that explicitly**

In general, the desirability functions $f_i$ can be quite complex and
may not be well behaved at all. People have all kinds of weird desires
or weird beliefs about how life in certain regions may be. In this
project it is impossible to recover the individual functions and
indeed it may be impossible in every practically conceivable study.
For example, these desirabilities are likely not stable across time,
they may even change during a single day, depending on mood etc. All
that we assume is that, for each person, who wants to move, there is
some desirability function that captures this person's *average*
desires with respect to a new home. Where this person moves to in the
end is random. The desires may change for example. A job application
in the favorite region may be unsuccessful, the search for a flat
takes to long but the person has to move very soon etc.

All we assume is that each persons desires can be described by such a
function for each individual and that the *aggregate* behavior of
groups of people can be described by much simpler functions. These
functions allow us to describe the behavior of groups of people with
reasonable errors, even though individual deviations may be large. We
assume that individuals consider the individual desirability functions
depend on: $P_r$ the population of $r$, $D_r$ is the distance of $i$'s
current home to the new destination, $\rho_r$ it's population density,
$L_r$ is the desirability of the wider region of $r$ and $\epsilon_r$
an unknown function of $i$ and $r$ that describes $i$'s idiosyncratic
desirability for $r$ that depends on a possibly very high dimensional
vector $\epsilon$. Formally,

$$
y_{ir} = f_i(P_r, D_r, \rho_r, L_r, \epsilon_r)
$$

We can not observe those function directly. Rather, we observe the
actions resulting from those latent desires: People change their
residence, they move somewhere else. To be able to infer their desires
(or rather aspects of their aggregated desires) from their observed
behavior we assume that the *capacity* of a region $\lambda(r)$
*exceeds* the average desire that a population ascribes to a region:
$\lambda(r) \geq \mu(r)$. The capacity **this is not thought out yet**
measures a region's ability to receive new migrants. Imagine, for
example cinemas in Germany show a documentary about a small village
where the happiest people in Germany live. The people of this village
tell their audience how incredibly beautiful this village is. The
documentary is a huge success and 1000 people want to move their, out
of a population of 10000 migrants. However the village does only have
3 empty houses and space to build 5 more. Assuming each host a family
of 4, only 32 people can move there. This would be a huge problem for
the analysis, since from the observed behavior we would estimate the
desirability for this region as $\tilde{\mu}(r) = 32 / 10000$ when in
fact the true desirability is $\mu(r) = 1000 / 10000$.

The rest of this section describes the desirability function in more
detail and explains how inferences about groups can be attempted,
starting with desirability as function of distance.

### Distance Desirability
Each migrant has some aversion to move across certain distances.
Countless studies from numerous places and times suggest that most
prefer locations nearby. First, we define the probability that migrant
$i$ moves exactly $z$ km. We need two definitions: That of a circle
and that of a disk.

\begin{align}
\tilde{C}_i(z) &= \{(x, y) \in \mathbb{R}^2 \mid \|(x - x_i, y - y_i)\| = z\} \\
C_i(z) &= \tilde{C}_i(z) \cap \mathcal{R} \\
\tilde{M}_i(z) &= \{(x, y) \in \mathbb{R}^2 \mid \|(x - x_i, y - y_i)\| \leq z\} \\
M_i(z) &= \tilde{M}_i(z) \cap \mathcal{R} \\
\end{align}

where \( \| \cdot \| \) denotes the Euclidean norm and $a$ denotes the
fraction of points of $C_i(z)$ and $M_i(z)$ that lies within Germany,
$a_{iz} = \lambda_1(C_i(z)) / \lambda_1(\tilde{C}_i(z)$, the length of
$C_i(z)$ is the one dimensional lebesque measure $\lambda_1(C_i(z)) =
a2\pi z $.

$C_i(z)$ describes the circumference of a circle around $i$'s present
home, only points are considered that are within Germany. Assume for
example that $i$ lives 10km away from the border. Then much of a
circle with radius 20km will be outside Germany and, since we only
consider internal migration, $i$ can not move there.
$M_i(z)$ is the disk with radius $z$ around $i$'s present home.

Formally a person's attitudes towards distance are defined as

$$
\tilde{f}_i(z) := \frac{1}{a2\pi z} \int_{C_i(z)} f_i(x, y)d(x,y)
$$

We may look now at populations of $N$ migrants, such that this
populations attitudes towards distance are defined as: $\tilde{f}(z) =
\frac{1}{N}\sum_{i = 1}^N \tilde{f}_i(z)$ 

$$
\providecommand{\senscond}[1]{& \text{if } \tilde{f}(z) #1 \quad\text{for all } z}
\text{Population type of } = 
\begin{cases}
\text{Distance-Indifferent} \senscond{= 1} \\
\text{Proximal-Preferring} \senscond{ < \frac{1}{z}} \\
\text{Distance-Decay Sensitive} \senscond{ = \frac{1}{z}}\\
\text{Distance-Seeking} \senscond{ > 1} \\
\end{cases}
$$

**well for all z? Or all z such that moves is within Germany**
Theoretically interesting are in particular the first two population
types. An utter indifference to distance or even a preference for far
away regions would be greatly surprising since countless studies from
numerous places and periods have shown otherwise. We can, however,
easily imagine distance insensitive migrations. Some people may have a
very strong desire to study a particular rare subject or learn a rare
skill, that is only taught in very few places. To them it does not
matter how far away it is, they will move there. If they acquire these
skills then maybe only in very few other regions are jobs available.
Others maybe moved often and now feel the strong desire to return
home. Home may be far away but they will move. Again others may work
from remote and inherit a beautiful house at the other end of Germany.
While all this seems conceivable, there is in fact no empirical
evidence that this population type matters for moves between German
districts.

The probability $i$ moves across a certain distance $z$ equals $i$'s
average desirability they attribute to this distance times the
opportunities:

$$
g_i(z) = \tilde{f}_i(z) a2\pi z 
$$

We assume that each person can move at most $m$ km. We say a
population is distance insensitive if

$$P(D \leq r) = G(m) = \frac{r^2}{m^2} \quad
\text{for all } 0 \leq r \leq m 
$$

We say a population is distance avoidant if

\begin{align}
G(m) &\geq \frac{r^2}{m^2} \text{ for all } r \leq \tilde{r} \quad \text{and} \\
G(m) &\leq \frac{r^2}{m^2} \text{ for all } r \geq \tilde{r} \quad \text{ for some } 0 \leq \tilde{r} \leq m
\end{align}

We say a population is distance seeking if

\begin{align}
G(m) &\leq \frac{r^2}{m^2}  \text{ for all } r \leq \tilde{r} \quad \text{and} \\
G(m) &\geq \frac{r^2}{m^2} \text{ for all } r \geq \tilde{r} \quad \text{ for some } 0 \leq \tilde{r} \leq m
\end{align}


In other words, a population is distance insensitive if their
desirability for a disk centered at their current home equals the area
of this region. Since $\text{area}(M_i(r)) = \pi r^2$, desirability of
a distance insensitive population grows quadratically with distance.
Let us now understand what that means in terms of individual
desirability functions. First, observe that **I am not sure if this
d(x, y) is standard notation. I guess it is clear enough that I mean
to integrate 1 over all points of the set and anyway, we only use this
as definition, not for any calculations.** $\int_{M(r)} 1 d(x, y) =
\int_0^r 2 \pi x dx$. That is the area of a disk with radius $m$ can
be calculated by adding all the infinitesly small circles with
circumference $2\pi x$ that are contained within $M$.

The probability that migrant $i$ moves at most $m$ km is defined as

\begin{align}
G_i(m) = P(D(i) \leq m) &:= \int_{M_i(m)} f_i(x, y) d(x, y) \\
&= \int_0^r 2\pi \tilde{f}_i(x) dx \quad \text{where}\\
g_i(r) = \tilde{f}_i(r) &= \int_{C_i(r)} f_i(x, y) d(x, y)
\end{align}

The individual distance desirability functions $g_i(r)$ are
considerably simpler than the individual desirability functions $f_i$.
They are one dimensional functions, they aggregate a lot and we assume
that they are continuous. This assumption seems reasonable. $g_i(r)$
is the total desirability that $i$ ascribes to all points that are
exactly $r$km away. $g_i(r + \epsilon)$ is the total desirability of
points that are only a tiny bit farther away. These points will share
many charactersitics of points that are $r$km away. Since the $f_i$
can be discontinuous, $g_i$ can be as well but to simplify the
analysis we assume them as continuous and note that this seems
reasonable, especially for larger radii where $g_i$ averages over many
points. **g always averages over many points since R is uncountable.
Some more technical language would be good here**

We define a segmentation of the population $\mathcal{P}$ of $N$
migrants into $G$ groups with $N_g$ members each, $G \leq N$ as
follows: All members within each group $g$ have a similar distance
desirability function: $G_i(m) \approx G_j(m)$ for all $m \geq 0$, all
$i, j \in g$ and all $g$. This is merely a definition. Formally we may
define similarity precisely and if distance desirability functions are
dissimilar, we define a new group. At most, we will have $G = N$
groups, but it is quite likely that we arrive at much fewer groups.
**example**.  
We assume that these groups can be grouped into two broad groups $G_I$
and $G_H$, such that The probability that a member of each group
migrates at most $m$km, $P(D_I \leq m)$ and $P(D_H \leq m)$ can be
expressed as integral over densities $g_I$ and $g_H$

Further, we propose a function $g(r) = \tilde{f}$, that describes a
populations distance sensitivity. The function is

\begin{align}
g(x) &=  B {(x + \delta)^\gamma} \quad \text{where} \\
B &= \frac{c + 1}{(m + \delta)^{c + 1} - \delta^{c + 1}} \quad  
\text{is a normalization constant such that} \\
&\int_0^m g(x) dx = 1 \quad  \text{for } \delta > 0 \text{ and } \gamma \neq 1 
\end{align}

**prove that g(x) is indeed a density: g >= 0 and G(m) = 1**

Then $g(x)$ characterizes the sensitivity type of the population
**distance insensitive does not exactly work out since $(x + \delta)^\gamma$ does not exactly behave quadratically in x**
$$
\providecommand{\tif}{\text{ if }}
\text{Distance type} = 
\begin{cases}
\text{insensitive} & \tif c = 2 \\
\text{avoidand} & \tif c < 2 \\
\text{seeking} & \tif c > 2
\end{cases}
$$

```{julia}
#| label: fig-cdf
#| fig-cap: "Different sensitivities, blue: distance avoidant, red: insensitive, green: seeking. The red cdf as function of the area should be a straight line with y = x. This would work with delta = 0."

cdfplots()

```

<!-- Some words about what we did so far and why it matters. Distance is an -->
<!-- important predictor that explains a lot of the variability in observed -->
<!-- origin-destination flows. Furthermore, people's attitudes to distance -->
<!-- tell us a lot about who they are and what their motives may be. Most -->
<!-- people do not want to move far, they are *close movers*. They oppose -->
<!-- far moves. -->

<!-- In this group, the individual distance desirability functions may look -->
<!-- very different, but in aggregate this group does not favor any given -->
<!-- distance, they are distance insensitive.   -->
<!-- To get some intuition for all of that, consider Tom and Sarah. Both -->
<!-- finished their education and now they desperately want to start a -->
<!-- professional training as porcelain painter, which is only possible in -->
<!-- Meißen, in the Free State of Saxony in Eastern Germany. Their desire -->
<!-- is so strong that it dwarfs everything else. How may their distance -->
<!-- desirability functions look like? First, although their desire to -->
<!-- become a porcelain painter is the most important in their life, they -->
<!-- have other desires as well. Both like to be near their home, where all -->
<!-- their friends and family are. To simplify things, we assume this are -->
<!-- the only two things they care about. Tom already lives in Meißen but -->
<!-- Sarah lives 500km away (see @fig-gex). -->


<!-- ```{julia} -->
<!-- #| label: fig-gex -->
<!-- #| fig-cap: "Hypothetical distance desirability functions g for Sarah and Tom. The greatest wish of both is to become a porcelain painter and the only place to learn this is in Meißen. Tom already lives there but Sarah lives 500km away. Both also want to be close to their home where friends and family live. Both desire being a porcelain painter more than being close to their home and Tom's and Sarah's desires are equally strong. The functions reflect that Tom does not have to sacrifice being close to his friends to become a porcelain painter." -->

<!-- x = range(1, 800, 1000) -->
<!-- plot() -->
<!-- ## better explicitly write down individual desirability functions and -->
<!-- ## plot the max as a function of distance -->
<!-- hypo!(range(1, 800, 100), [10, 500], [10, 10], [20, 10], "Sarah") -->
<!-- hypo!(range(1, 800, 100), [15], [10], [8], "Tom", -->
<!--       "Hypothetical Desirability \n for the study of porcelain painting in Meißen") -->

<!-- ``` -->

<!-- In this particular example Tom's and Sarah's distance desirability -->
<!-- functions are not very useful to understand their preferences for -->
<!-- Meißen. For this we need to look at another component of their -->
<!-- desirability functions $f$, namely the component modeling the -->
<!-- locational desirability. We return to their case below. For now, let's -->
<!-- discuss their distance preferences. Looking at @fig-gex, it may appear -->
<!-- as if Tom and Sarah have nothing in common. Their functions look very -->
<!-- different. But per assumption they have very much in common. Both -->
<!-- prefer the exact same things in the exact same way, what differs -->
<!-- —quite arbitrarily— is their place of birth. Even their distance -->
<!-- desirability functions share an important feature: Tom and Sarah are -->
<!-- indifferent to distance. To them, it does not matter how far away -->
<!-- Meißen is, they would move there anyway. Tom and Sarah are not alone. -->
<!-- Although there may be only a few people who want to study porcelain -->
<!-- painting, it appears that quite some people are insensitive to -->
<!-- distance. This may include people who have a specialized education and -->
<!-- who benefit financially a lot from a handful of employers that can -->
<!-- utilize their skills. Or people who moved around a lot just to realize -->
<!-- what they really long is their home. It does not matter how far away -->
<!-- it is, they will move there. Others may have met the love of their -->
<!-- life online and all they want is being close to their loved ones. -->

<!-- We assume that the population of migrants $P$ can be stratified into -->
<!-- two distinct groups, $I$ denoting distance insensitive migrants and $S$ -->
<!-- denoting distance sensitive migrants. $\phi = |I| / |P|$ denotes the -->
<!-- fraction of insensitive migrants. We assume further that the -->
<!-- probability a move is at most $m$ km can be expressed as -->

<!-- $$ -->
<!-- P(D(i) \leq m) = \phi + (1 - \phi)\int_0^m\frac{1}{(x + \delta)^\gamma}dx \quad  -->
<!-- \text{where } \gamma, \delta > 0 \text{ and } \delta \text{ small } -->
<!-- $$ -->


<!-- ```{julia} -->
<!-- #| label: fig-all-insensitive -->
<!-- #| fig-cap: "Mixture of all those who distance insensitive " -->
<!-- centers = [10 * i for i in 1 : 80] -->
<!-- sigmas = fill(10, 80) -->
<!-- fac = centers ./ 10 -->
<!-- plot() -->
<!-- hypo!(x, centers, sigmas, fac, -->
<!--       "all future porcelain painter", -->
<!--       "Mixture of distance insensitive\nwould-be porcelain painters") -->

<!-- ``` -->

