--- 
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
always_allow_html: true
---

```{r global_knitr, echo = FALSE, eval = TRUE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      results = "hide",
                      fig.width = 8,
                      fig.asp = 0.7,
                      out.width = "120%")

## ---
## title: "Using bookdown with Beamer"
## output:
##   bookdown::pdf_book:
##     base_format: "function(..., number_sections) rmarkdown::beamer_presentation(...)"
##     number_sections: false
## ---

```

```{r, packages-check}

library(data.table)
library(sf)
library(ggplot2)
library(MigStat)
library(plotR)
library(kableExtra)
library(patchwork)
source("../functions.R")
source("../functions_plots.R")

```

```{r load-data, message = TRUE}

setwd("/home/konstantin/Documents/GermanMigration/")
mod_name <- "esa"
data <- read_data(mod_name)
dt <- setnames(data$preds, c("flows", "preds"), c("actual", mod_name), skip_absent = TRUE)
dt[, model := NULL]
coefs <- data$coefs[, diff := values - inits]
dists <- fread("data/districts.csv")

dt[, gravity := predict(fit_gravity(.SD, offset = FALSE), type = "response"), keyby = .(agegroup)]
dtm <- melt(dt, measure.vars = c("gravity", mod_name),
            variable.name = "model", value.name = "preds")

kable(dt[, .(frac_0 = mean(actual == 0)), keyby = .(agegroup)], digits = 2)

```

```{r, real-data, eval = FALSE}

flows <- fread("data/FlowDataGermans.csv")
setnames(flows, "dist", "distance")
dt[flows, real := i.flows, on = .(fromdist, todist, year, agegroup)]
dt[real != 0][, mean(actual == real)]

kable(flows[, .(frac_0 = mean(flows == 0)), keyby = .(agegroup)], digits = 2)

```

```{r opti-ini-plot, results = "show"}

coefs_plt <- coefs[1:30]
kable(coefs_plt[, .(names, values, inits)], digits = 2, caption = "Optis and inits")

```

```{r, invent-flows, results = "show"}

invent <- dtm[, .(all_actual = sum(actual),
                 all_predicted = sum(preds)), keyby = .(agegroup, model)][
  , rel_diff := (all_actual - all_predicted) / all_actual][]
kable(dcast(invent, agegroup + all_actual ~ model, value.var = "all_predicted"),
    caption = "Do our models invent flows? Every column shows total flows: Observed and from two models")

```


```{r plots-fits}


p <- 1
sm <- TRUE
dtm[, actual_imp := as.double(actual)]
rnds <- rlnorm(dtm[actual == 0, .N], -5, log(2.0))
dtm[actual == 0, actual_imp := rnds]
plot_fit(dtm[model == mod_name],
         distance, log(actual_imp / preds, base = 10), th_min = 0, p_sample = p, smooth = sm)
ggsavew(w = 8, file = sprintf("../plots/%s.pdf", mod_name))
plot_fit(dtm[model == "gravity"],
         distance, log(actual_imp / preds), th_min = 0, p_sample = p, smooth = sm)
ggsavew(w = 8, file = "../plots/gravity.pdf")

dtm[, actual_imp := as.double(actual)]
rnds <- rlnorm(dtm[actual == 0, .N], 0, log(2.0))
dtm[actual == 0, actual_imp := rnds]
plot_fit(dtm[model %in% c(mod_name, "gravity")],
         distance, log(actual_imp / preds), th_min = 0, p_sample = p, smooth = TRUE)
ggsavew(w = 8, file = sprintf("../plots/%s_gravity.pdf", mod_name))

```

```{r frac0, results = "show"}

age_dt <- data.table(age = c("below18", "18-25", "25-30", "30-50", "50-65", "above65"),
                     julia = coefs_plt[25:30, names])

frac0 <- dtm[model == mod_name, .(actual_frac0 = mean(actual == 0)), keyby = .(agegroup)]

model0 <- coefs_plt[25:30, .(names, model_frac0 =  1 - (values / 1000))]
model0[age_dt, age := i.age, on = .(names = julia)]
frac0[model0, "one-mm" := model_frac0, on = .(agegroup = age)]
kable(frac0, digits = 2)


```

```{r correlations}

cors <- dcast(dtm[distance > 0, .(correlations = cor(log(actual_imp), log(preds))),
                  keyby = .(agegroup, model)], agegroup ~ model)
kable(cors, digits = 2, caption = "Correlation with actual flows")

```

```{r for-speech}

dtm[agegroup == "18-25"]
dtm[model == "gravity", model := "gravity1.0"]
dtm[model == "esa", model := "gravity2.0"]


plot_speech <- function(dt, age, main, color = TRUE) {    
    if(color == TRUE) {
        fit <-  ggplot(dt[agegroup == age],
                       aes(distance, log(actual/preds, base = 10),
                           color = model))
    }
    if(color == FALSE) {
        fit <-  ggplot(dt[agegroup == age],
                       aes(distance, log(actual/preds, base = 10)))
    }
    fit <- fit +
        geom_hline(yintercept = 0) +
        geom_point(alpha = .05, size =.5) +
        geom_smooth(se = FALSE, linewidth = 2) +
        theme_minimal() +
        ggtitle(main) +
        labs(caption = "internal migration flows of 30-50 year olds \nGermany, 2017, n = 50k") +
        xlab("distance in km")
   return(fit)
}


plot_speech(dtm, "30-50", main = "Comparison: Models for positive flows")
ggsavew(filename = "../plots/esa_both.pdf")

plot_speech(dtm[model == "gravity2.0"], "30-50", main = "Gravity 2.0", color = FALSE)
ggsavew(filename = "../plots/esa_gravity2.0.pdf")

plot_speech(dtm[model == "gravity1.0"], "30-50", main = "Gravity 1.0", color = FALSE)
ggsavew(filename = "../plots/esa_gravity1.0.pdf")


```

```{r distance-state-plot, eval = FALSE}


dt[dists, frombl := i.bl_ags, on = .(fromdist = distcode)]
dt[dists, tobl := i.bl_ags, on = .(todist = distcode)]
dt[dists, fromdens := i.density, on = .(fromdist = distcode)]
dt[dists, todens := i.density, on = .(todist = distcode)]


all <- dt[, .(all = sum(actual)), keyby = .(agegroup, year)]
dt[all, ww := actual / i.all, on = .(agegroup, year)]
dt[, fromsax := fifelse(frombl == 14, TRUE, FALSE)]
dt[, tosax := fifelse(tobl == 14, TRUE, FALSE)]

test <- dt[(fromsax == TRUE & tosax == FALSE) | (fromsax == FALSE & tosax == TRUE),
   .SD[sample(.N, size = min(.N, 1e3))], keyby = .(tosax, fromsax)]

melt(test[, .(tosax, fromsax, agegroup, distance)],
     id.vars = "agegroup", )

ggplot(test,
       aes(distance) +
    geom_density(linewidth = 2) +
    facet_wrap(vars(agegroup)) +
    theme_minimal()

ggplot(rbind(sample_in, sample_out),
       aes(distance, color = type)) +
    geom_density(linewidth = 2) +
    facet_wrap(~agegroup) +
    theme_minimal()

ggsavew(filename = "~/Desktop/inout.pdf")

```

```{r distance-zeroflows, eval = FALSE}

flows[, zero_flows := fifelse(flows == 0, "zeroflow", "nonzeroflow")]
setnames(flows, "dist", "distance")
flows[dists, fromdens := i.density, on = .(fromdist = distcode)]
flows[dists, todens := i.density, on = .(todist = distcode)]

ggplot(flows, aes(distance, fill = zero_flows)) +
    geom_density(alpha = .2) +
    facet_wrap(~agegroup) +
    theme_minimal()
ggsavew(filename = "plots/distance_zero.pdf")

?geom_hex

flows[, distance_cut := cut_qs(distance, 6)]

ggplot(flows[agegroup == "18-25" & zero_flows == "zeroflow"], aes(log(fromdens), log(todens)) ) +
    geom_hex() +
    facet_wrap(vars(distance_cut, agegroup), scales = "free")
ggsavew(filename = "plots/zero_hex.pdf")

ggplot(flows[agegroup == "18-25"],
       aes(log(frompop), log(topop)) ) +
    geom_hex() +
    facet_wrap(vars(zero_flows, agegroup), scales = "free")



flows[flows == 0, .(min_dist = min(distance)), keyby = .(agegroup)]
flows[flows == 0 & distance == 21]

?geom_hex

ggplot(flows, aes(agegroup, distance, fill = agegroup)) +
    geom_violin() +
    facet_wrap(~zero_flows) +
    theme_minimal()
ggsavew(filename = "plots/zero_violin.pdf")

```
